# container aliases
if command -v docker &>/dev/null; then
  alias d='docker'
  alias dc='docker compose'
  alias dce='docker compose exec'
  alias dcps='docker compose ps --format="table {{.Name}}\t{{.Status}}\t{{.Ports}}"'
  alias dcstop='dc stop --timeout=1'
  alias dcup='docker compose up --detach --timeout=1'
  alias dgc='docker system prune -a --force --filter=until=720h'
  alias dps='docker ps --format="table {{.Names}}\t{{.Status}}\t{{.Ports}}"'
elif command -v container &>/dev/null; then
  alias d='container'
  alias dc='container-compose'
  alias dce='container-compose exec'
  alias dcstop='container-compose down'
  alias dcup='container-compose up --detach --timeout=1'
  alias dps='container list'
fi

# git aliases
alias ga='git add --all'
alias gb='git branch'
alias gc='git commit'
alias gcl='git clone'
alias gco='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gds='git diff --stat'
alias gf='git fetch --prune'
alias gff='git merge --ff-only'
alias gsh='git show'
alias gshs='git show --stat'
alias gj='git merge --no-ff'
alias gl='git log --graph --abbrev-commit --date=human'
alias gla='gl --all --remotes'
alias glp='git log --patch'
alias gls='gl --stat'
alias gm='git commit --amend --date=now'
alias gp='git push'
alias gpu='git push --set-upstream'
alias gr='git reset'
alias gra='git rebase --abort'
alias grb='git rebase'
alias grc='git rebase --continue'
alias grh='git reset --hard'
alias gri='git rebase --interactive'
alias gs='git status -sb'
alias gt='git stash'
alias gtp='git stash pop'

# other aliases
alias neovide='neovide --fork'
alias nv='nvim'
alias py='python3'
